services:
  postgres:
    image: postgres:16-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data # Named volume
    expose:
      - "5432" # Documents the port only used internally (Postgres is listening)
    networks:
      - wolf-wallet-net

  wolf-wallet-app:
    image: wolfgangkp/wolf-wallet:latest
    env_file:
      - .env
    expose:
      - "5000"
    depends_on:
      - postgres
    networks:
      - external
      - wolf-wallet-net

volumes:
  postgres_data:

networks:
  external:
    external: true
  wolf-wallet-net:
    internal: true
